version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: precious
    #   MONGO_INITDB_ROOT_PASSWORD: Owolabi$1
    volumes:
      - mongodb_data:/data/db
    networks:
      - p-pay-net

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
        - p-pay-net

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:5000/api/
      - NEXT_PUBLIC_PAYSTACK_KEY=pk_test_2bd1847db9309248327cc9df2228692b4b9b91f6
    depends_on:
      - server
    networks:
      - p-pay-net

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - rabbit
    environment:
      - COOKIE_SECRET=G0k/!z#'g[L_*!6-F+}"|4t`XtV20z
      - JWT_TOKEN=kxts7?x}n+g~[mARSIMB6lsx$PTR>L
      - MONGO_URL=mongodb://mongodb:27017/P-PAY
      - PORT=5000
      - CLIENT_ORIGIN=http://client:3000
      - RABBIT_URL=amqp://rabbit
      - EMAIL_CONNECTION_STRING='endpoint=https://p-pay-communication-service.communication.azure.com/;accesskey=qhqFNLb6JC6lol1RgxRmu1ZuUGmMWNI38FpQI1IR5ljUYVCPq6M0LWG9RW+tMl8UqMEP+aRSpacjX/NIke/Ucg=='
      - PAYSTACK_SECRET_KEY=sk_test_916d4ca3213a3f65ef450bff228f76ee41a3808e
    stdin_open: true
    tty: true
    networks:
      - p-pay-net

networks:
  p-pay-net:

volumes:
  mongodb_data:
  rabbitmq_data:
