version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: precious
    #   MONGO_INITDB_ROOT_PASSWORD: Owolabi$1
    volumes:
      - mongodb_data:/data/db
    networks:
      - p-pay-net

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
        - p-pay-net

networks:
  p-pay-net:

volumes:
  mongodb_data:
  rabbitmq_data:

